//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace Netron.NetronLight.Demo.BugWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NetronWSBinding", Namespace="http://mysql-n.sourceforge.net/webservice/")]
    public partial class NetronWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddBugOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListBugsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NetronWS() {
            this.Url = global::Netron.NetronLight.Demo.Properties.Settings.Default.Demo_BugWS_NetronWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddBugCompletedEventHandler AddBugCompleted;
        
        /// <remarks/>
        public event ListBugsCompletedEventHandler ListBugsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://netron.sourceforge.net/ewiki/NetronBugLoggingService.php/AddBug", RequestNamespace="http://soapinterop.org/", ResponseNamespace="http://soapinterop.org/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string AddBug(string bugtitle, string bugtext) {
            object[] results = this.Invoke("AddBug", new object[] {
                        bugtitle,
                        bugtext});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddBugAsync(string bugtitle, string bugtext) {
            this.AddBugAsync(bugtitle, bugtext, null);
        }
        
        /// <remarks/>
        public void AddBugAsync(string bugtitle, string bugtext, object userState) {
            if ((this.AddBugOperationCompleted == null)) {
                this.AddBugOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddBugOperationCompleted);
            }
            this.InvokeAsync("AddBug", new object[] {
                        bugtitle,
                        bugtext}, this.AddBugOperationCompleted, userState);
        }
        
        private void OnAddBugOperationCompleted(object arg) {
            if ((this.AddBugCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddBugCompleted(this, new AddBugCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://netron.sourceforge.net/ewiki/NetronBugLoggingService.php/ListBugs", RequestNamespace="http://mysql-n.sourceforge.net/webservice/", ResponseNamespace="http://mysql-n.sourceforge.net/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string[] ListBugs(string last) {
            object[] results = this.Invoke("ListBugs", new object[] {
                        last});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ListBugsAsync(string last) {
            this.ListBugsAsync(last, null);
        }
        
        /// <remarks/>
        public void ListBugsAsync(string last, object userState) {
            if ((this.ListBugsOperationCompleted == null)) {
                this.ListBugsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListBugsOperationCompleted);
            }
            this.InvokeAsync("ListBugs", new object[] {
                        last}, this.ListBugsOperationCompleted, userState);
        }
        
        private void OnListBugsOperationCompleted(object arg) {
            if ((this.ListBugsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListBugsCompleted(this, new ListBugsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddBugCompletedEventHandler(object sender, AddBugCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddBugCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddBugCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListBugsCompletedEventHandler(object sender, ListBugsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListBugsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListBugsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591